"""initial schema

Revision ID: 0117765b13a5
Revises: bdf17b3d2dcd
Create Date: 2026-04-22 16:04:44.602337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0117765b13a5'
down_revision: Union[str, Sequence[str], None] = 'bdf17b3d2dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=225), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arenas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('goal', sa.String(length=20), nullable=False),
    sa.Column('completion_status', sa.Boolean(), nullable=True),
    sa.Column('theme_key', sa.String(length=50), nullable=True),
    sa.Column('user_key', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_key'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('length_minutes', sa.Integer(), nullable=True),
    sa.Column('completion_status', sa.Boolean(), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('arena_key', sa.Integer(), nullable=True),
    sa.Column('user_key', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arena_key'], ['arenas.id'], ),
    sa.ForeignKeyConstraint(['user_key'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    op.drop_table('arenas')
    op.drop_table('users')
    # ### end Alembic commands ###
